Vasb 10235 add percentage processed on map index view
viewar/appfiles-master-react-admin pull request #19
Opened 2020-12-14 08:05 UTC by JauntAR

This PR addresses: http://jira.viewar.com/browse/VASB-10235

"Add percentage processed on map index view"

Switch from using created to updated on Map Index view
Sort now uses Updated instead of Created attribute
Navigation.php has been updated to accommodate these changes

2020-12-14 08:58 UTC, kh-viewar requested changes
See redundant .dev in .viewar-config.

2020-12-14 08:58 UTC, kh-viewar commented on appfiles/reactmaster-admin/.viewar-config
> +  "appId": "com.viewar.reactmaster.admin.dev",
This will break the CircleCI configuration if we add .dev in here (will deploy to com.viewar.reactmaster.admin.dev.dev)

2020-12-14 09:05 UTC, JauntAR commented on appfiles/reactmaster-admin/.viewar-config
> +  "appId": "com.viewar.reactmaster.admin.dev",
Sorry I committed that by accident, will remove

2020-12-15 07:26 UTC, kh-viewar approved these changes

2020-12-15 07:39 UTC, merged